### ISSUE TITLE
Run python script once a month

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/SelectStar#5]
https://github.com/lifeparticle/SelectStar/blob/master/.github/workflows/python-app.yml

**Comment by Pratham-Gaikwad** [comment]
hi @lifeparticle  i would like to work on this issue . Could you give more details about what do you exactly want to be done

**Comment by lifeparticle** [comment]
@Pratham-Gaikwad thank you for interest in the project. We need to update the [GitHub actions](https://github.com/lifeparticle/SelectStar/blob/main/.github/workflows/python-app.yml) to run the cron job at the beginning of each month.

**Comment by Pratham-Gaikwad** [comment]
Thank I'll solve this issue
